

[tool.towncrier]

   package = "{{cookicutter.package_name}}"
   package_dir = "src"
   filename = "CHANGELOG.rst"
   template = "changelog.d/towncrier_template.rst"
   issue_format = "`#{issue} <https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}/issues/{issue}>`_"
   directory = "changelog.d"
   title_format = "{version} ({project_date})"
   underlines = ["-", "^"]

   [[tool.towncrier.section]]
       path = ""

   [[tool.towncrier.type]]
       name = "Backward-incompatible Changes"
       showcontent = true

   [[tool.towncrier.type]]
       name = "Deprecations"
       showcontent = true

   [[tool.towncrier.type]]
       name = "Changes"
       showcontent = true
